const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const {createRequire} = require('node:module');
const root = '/Users/fabiofranzini/GitHub/apvee/spfx-react-toolkit';
const requireRepo = createRequire(path.join(root, 'package.json'));
const webpack = requireRepo('webpack');
const {chromium} = require('/Users/fabiofranzini/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const fixture = __dirname;
const output = path.join(root, '.docs/maintenance/evidence/tree-shaking/task-6/browser');
fs.mkdirSync(output, {recursive:true});
const panel = path.join(root,'apps/spfx-react-toolkit-test/src/webparts/spFxReactToolkitTest/components/panels/ImportsPanel');
fs.writeFileSync(path.join(fixture,'entry.tsx'), `import * as React from 'react';\nimport * as ReactDOM from 'react-dom';\nimport {initializeIcons} from '@fluentui/react/lib/Icons';\nimport ImportsPanel from ${JSON.stringify(panel)};\ninitializeIcons('/fonts/');\nReactDOM.render(<ImportsPanel />, document.getElementById('root'));\n`);
fs.writeFileSync(path.join(fixture,'index.html'), '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ImportsPanel actual local browser fixture</title><style>body{margin:16px;font-family:Segoe UI,sans-serif;}main{max-width:1200px;margin:auto;}</style></head><body><main><h1>Imports panel local browser fixture</h1><p>Actual sample panel and compiled package. This is not authenticated SharePoint validation.</p><div id="root"></div></main><script src="fixture.js"></script></body></html>');
const observations=[], failures=[], consoleEvents=[], pageErrors=[], requestFailures=[];
let browser, server, page, url;
function check(name,actual,expected){const pass=JSON.stringify(actual)===JSON.stringify(expected); observations.push({name,actual,expected,pass});if(!pass)failures.push(name);}
function card(scope){return page.locator(`[data-imports-demo="${scope}"]`);}
function preview(scope){return page.locator(`[data-imports-demo="${scope}-preview"]`);}
async function style(scope){return preview(scope).evaluate(el=>{const s=getComputedStyle(el);return {width:s.width,paddingLeft:s.paddingLeft,paddingRight:s.paddingRight,fontFamily:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight};});}
async function settle(){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function counter(scope,label){return card(scope).locator('p').filter({hasText:label}).textContent();}
async function overflow(){return page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth, offenders:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.right>innerWidth+1||r.left < -1;}).map(e=>({tag:e.tagName,probe:e.getAttribute('data-imports-demo'),text:e.textContent.slice(0,100),left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right}))}));}
(async()=>{
await new Promise((resolve,reject)=>webpack({context:root,mode:'production',devtool:'source-map',entry:path.join(fixture,'entry.tsx'),output:{path:fixture,filename:'fixture.js'},resolve:{extensions:['.tsx','.ts','.js'],modules:[path.join(root,'node_modules'),'node_modules']},resolveLoader:{modules:[path.join(root,'node_modules')]},externals:[({request},done)=> /^@microsoft\/sp-/.test(request||'') ? done(null, `commonjs ${request}`) : done()],optimization:{minimize:false,usedExports:true,sideEffects:true},module:{rules:[{test:/\.tsx?$/,use:path.join(root,'scripts/sx-browser-typescript-loader.cjs')}]},performance:{hints:false}},(err,stats)=>{fs.writeFileSync(path.join(output,'build.log'),err?String(err):stats.toString({all:false,assets:true,timings:true,warnings:true,errors:true}));if(err||stats.hasErrors())return reject(err||new Error(stats.toString({all:false,errors:true})));const report=stats.toJson({all:false,modules:true,chunkModules:true});fs.writeFileSync(path.join(output,'webpack-modules.json'),JSON.stringify(report,null,2));const bundle=fs.readFileSync(path.join(fixture,'fixture.js'),'utf8');check('no emitted SPFx host requires',/require\([\"']@microsoft\/sp-/.test(bundle),false);check('no emitted SPFx SDK implementation',/SPCoreLibraryStrings|MSGraphClientV3|PropertyMetadataProcessor/.test(bundle),false);resolve();}));
server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/favicon.ico'){res.writeHead(204).end();return;}const isFont=pathname.startsWith('/fonts/');const base=isFont?path.join(root,'node_modules/@fluentui/font-icons-mdl2/fonts'):fixture;const file=path.resolve(base,pathname==='/'?'index.html':isFont?pathname.slice(7):'.'+pathname);if(!file.startsWith(base+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.woff')?'font/woff':'application/javascript');res.end(data);});});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});url=`http://127.0.0.1:${server.address().port}`;
browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,ignoreDefaultArgs:['--hide-scrollbars']});
page=await browser.newPage({viewport:{width:1440,height:1000}});
page.on('console',m=>consoleEvents.push({type:m.type(),text:m.text()}));page.on('pageerror',e=>pageErrors.push(e.message));page.on('requestfailed',r=>requestFailures.push({url:r.url(),error:r.failure()}));
await page.goto(url);await preview('legacy').waitFor();await settle();await page.evaluate(()=>document.fonts.ready);
check('page identity',await page.title(),'ImportsPanel actual local browser fixture');check('page origin',new URL(page.url()).origin,url);check('all actual sample cards',await page.locator('[data-imports-demo="root"],[data-imports-demo="domain"],[data-imports-demo="legacy"]').count(),3);check('no framework overlay',await page.locator('webpack-dev-server-client-overlay,#webpack-dev-server-client-overlay,nextjs-portal').count(),0);
await page.screenshot({path:path.join(output,'desktop-initial.png'),fullPage:true});
const initialStyles={}, initialClasses={};
for(const scope of ['root','domain','legacy']){initialStyles[scope]=await style(scope);initialClasses[scope]=await preview(scope).getAttribute('class');check(`${scope}: initial width`,initialStyles[scope].width,'240px');check(`${scope}: LTR start padding`,initialStyles[scope].paddingLeft,'16px');check(`${scope}: LTR opposite padding`,initialStyles[scope].paddingRight,'0px');}
check('equivalent initial computed styles',Object.values(initialStyles),[initialStyles.root,initialStyles.root,initialStyles.root]);check('equivalent initial classes',Object.values(initialClasses),[initialClasses.root,initialClasses.root,initialClasses.root]);
for(const [index,scope] of ['root','domain','legacy'].entries()){for(let n=0;n<index+1;n++)await card(scope).getByRole('button',{name:'Increment counter',exact:true}).click();await card(scope).getByRole('button',{name:'Invoke original callback',exact:true}).click();check(`${scope}: independent current`,await counter(scope,'Current counter:'),`Current counter: ${index+1}`);check(`${scope}: captured callback latest state`,await counter(scope,'Observed counter:'),`Observed counter: ${index+1}`);check(`${scope}: callback identity`,await counter(scope,'Same callback identity:'),'Same callback identity: yes');}
for(const [index,scope] of ['root','domain','legacy'].entries())check(`${scope}: retained independent count`,await counter(scope,'Current counter:'),`Current counter: ${index+1}`);
const overrides={},overrideClasses={};
for(const scope of ['root','domain','legacy']){await card(scope).getByRole('button',{name:'Apply width override',exact:true}).click();overrides[scope]=await style(scope);overrideClasses[scope]=await preview(scope).getAttribute('class');check(`${scope}: override width`,overrides[scope].width,'360px');}
check('equivalent override styles',Object.values(overrides),[overrides.root,overrides.root,overrides.root]);check('equivalent override classes',Object.values(overrideClasses),[overrideClasses.root,overrideClasses.root,overrideClasses.root]);await page.screenshot({path:path.join(output,'desktop-overrides.png'),fullPage:true});
for(const scope of ['root','domain','legacy']){await card(scope).getByRole('button',{name:'Remove width override',exact:true}).click();check(`${scope}: restored width`,(await style(scope)).width,'240px');check(`${scope}: restored classes`,await preview(scope).getAttribute('class'),initialClasses[scope]);}
await page.locator('[data-imports-demo="direction"]').click();check('active provider RTL',await page.locator('[data-imports-demo="provider"]').getAttribute('dir'),'rtl');
for(const scope of ['root','domain','legacy']){check(`${scope}: RTL start padding`,(await style(scope)).paddingRight,'16px');check(`${scope}: RTL opposite padding`,(await style(scope)).paddingLeft,'0px');}
await page.screenshot({path:path.join(output,'desktop-rtl.png'),fullPage:true});await page.locator('[data-imports-demo="direction"]').click();for(const scope of ['root','domain','legacy'])check(`${scope}: restored LTR padding`,(await style(scope)).paddingLeft,'16px');
const desktopOverflow=await overflow();observations.push({name:'desktop overflow inspection',actual:desktopOverflow});check('desktop no page overflow',desktopOverflow.scrollWidth<=desktopOverflow.innerWidth+1,true);
await page.setViewportSize({width:390,height:844});await settle();const mobileOverflow=await overflow();observations.push({name:'mobile overflow inspection',actual:mobileOverflow});check('mobile no page overflow',mobileOverflow.scrollWidth<=mobileOverflow.innerWidth+1,true);for(const scope of ['root','domain','legacy'])check(`${scope}: mobile controls visible`,await card(scope).getByRole('button',{name:'Increment counter',exact:true}).isVisible(),true);await page.screenshot({path:path.join(output,'mobile-initial.png'),fullPage:true});
await card('root').getByRole('button',{name:'Apply width override',exact:true}).click();const mobileOverrideOverflow=await overflow();observations.push({name:'mobile override overflow inspection',actual:mobileOverrideOverflow});check('mobile override no page overflow',mobileOverrideOverflow.scrollWidth<=mobileOverrideOverflow.innerWidth+1,true);await page.screenshot({path:path.join(output,'mobile-override.png'),fullPage:true});
fs.writeFileSync(path.join(output,'final-dom.txt'),await page.locator('body').innerText());check('unexpected console warning/errors',consoleEvents.filter(e=>['error','warning'].includes(e.type)),[]);check('page errors',pageErrors,[]);check('failed requests',requestFailures,[]);
})().catch(e=>failures.push(e.stack||e.message)).finally(async()=>{const version=browser?browser.version():'not launched';if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));const result={url,browser:version,fallback:'Browser plugin not available; existing cached Playwright with installed Chrome',boundary:'Actual sample ImportsPanel and actual compiled canonical root/domain/legacy package imports; generic local fixture. Authenticated SharePoint host NOT EXECUTED.',fixture,observations,failures,consoleEvents,pageErrors,requestFailures};fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({browser:version,checks:observations.length,failures,output},null,2));if(failures.length)process.exitCode=1;});
